/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import static java.awt.image.ImageObserver.HEIGHT;
import javax.swing.table.DefaultTableModel;
import models.ITransferDtVentas;
import webservicebar.WebServiceBar_Service;
import webservicebar.WebServiceBar;
import webservicebar.VwDetalleVentas;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import webservicebar.DetalleVenta;

/**
 *
 * @author brand
 */
public class FormAdminVentas extends javax.swing.JPanel implements ITransferDtVentas {

    /**
     * Creates new form FormAdminVentas
     */
    DefaultTableModel model;
    WebServiceBar_Service servicio;
    WebServiceBar cliente;
    DetalleVenta detalles;

    public FormAdminVentas() {
        initComponents();
        servicio = new WebServiceBar_Service();
        cliente = servicio.getWebServiceBarPort();
        detalles = new DetalleVenta();
        detalles.setIdDetalle(0);
        model = new DefaultTableModel();
        model.addColumn("idDetalle");
        model.addColumn("idProducto");
        model.addColumn("Producto");
        model.addColumn("Cantidad");
        model.addColumn("idVenta");
        model.addColumn("Precio");
        model.addColumn("Descuento");
        jTable2.setModel(model);
        limpiar();
    }

    @Override
    public void transferirDatos(int id) {
        llenarTabla(id);
        detalles.setIdVenta(id);
    }

    private void limpiar() {
        txtProducto.setText("");
        spnCantidad.setValue(0);
        detalles.setIdDetalle(0);
    }

    private void llenarTabla(int id) {
        List<VwDetalleVentas> detalles = new ArrayList<VwDetalleVentas>();

        detalles = cliente.buscarVenta(id);

        model.setRowCount(0);
        for (VwDetalleVentas dt : detalles) {
            model.addRow(new Object[]{dt.getIdDetalle(), dt.getIdProducto(), dt.getProduco(), dt.getCantidad(), dt.getIdVenta(), dt.getPrecio(), dt.getDescuento()});
        }
        jTable2.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSelectVenta2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnModifcar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        txtProducto = new javax.swing.JTextField();
        spnCantidad = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(0, 0, 0));

        btnSelectVenta2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnSelectVenta2.setText("Seleccionar Venta");
        btnSelectVenta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectVenta2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Producto:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cantidad:");

        btnModifcar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnModifcar.setText("Modificar");
        btnModifcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifcarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        txtProducto.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSelectVenta2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnModifcar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(spnCantidad))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane2)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnSelectVenta2)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModifcar)
                            .addComponent(btnEliminar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectVenta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectVenta2ActionPerformed
        FormBuscarVenta bv = new FormBuscarVenta(this);

        bv.setVisible(true);
    }//GEN-LAST:event_btnSelectVenta2ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int fila = jTable2.getSelectedRow();
        detalles.setIdDetalle(Integer.parseInt(jTable2.getValueAt(fila, 0).toString()));
        detalles.setIdProducto(Integer.parseInt(jTable2.getValueAt(fila, 1).toString()));
        String nombreProducto = jTable2.getValueAt(fila, 2).toString();
        int cantidadProd = Integer.parseInt(jTable2.getValueAt(fila, 3).toString());

        txtProducto.setText(nombreProducto);
        spnCantidad.setValue(cantidadProd);
    }//GEN-LAST:event_jTable2MouseClicked

    private void btnModifcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifcarActionPerformed
        if (detalles.getIdDetalle() == 0) {
            JOptionPane.showMessageDialog(this, "Tienes que seleccionar un detalle de venta para poder editarlo");
        } else {
            detalles.setCantidad(Integer.parseInt(spnCantidad.getValue().toString()));

            if (cliente.modificarDetalleVenta(detalles)) {
                JOptionPane.showMessageDialog(this, "El detalle de venta fue actualizado correctamente.");
                limpiar();
                llenarTabla(detalles.getIdVenta());
            } else {
                JOptionPane.showMessageDialog(this, "Ocurrio un error, la cantidad de productos no es suficiente para poder realizar esta venta.");
            }
        }
    }//GEN-LAST:event_btnModifcarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (detalles.getIdDetalle() == 0) {
            JOptionPane.showMessageDialog(this, "Tienes que seleccionar un detalle de venta para poder eliminarlo");
        } else {
            int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar este detalle de venta?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                if (cliente.eliminarDetalleVenta(detalles.getIdDetalle())) {
                    JOptionPane.showMessageDialog(this, "El detalle de venta fue eliminado.");
                    limpiar();
                    llenarTabla(detalles.getIdVenta());
                } else {
                    JOptionPane.showMessageDialog(this, "Ocurrio un error al eliminar el detalle de venta.");
                }
            }

        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModifcar;
    private javax.swing.JButton btnSelectVenta2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables

}
